### PR TITLE
Adapt old async to master & async methods

### PR DESCRIPTION
**Pull request by XeCycle**
Conflicts resolved are listed in the message of merge commit.

I noticed branch `nil` tried to implement async methods, but quite incomplete.  So I wrote async methods myself.

### CODE REVIEW

**Comment by XeCycle** [comment]
Sorry I forgot to pass async-p to parse-function-expr.  Added a bugfix commit; if you think all these looks okay I will squash it into "parse async methods".

Btw do we have a fixed policy on what proposals are ok to implement?  Decide on stage (e.g. >=3) or popularity, or simply reject all?

**Comment by dgutov** [comment]
> Sorry I forgot to pass async-p to parse-function-expr. Added a bugfix commit; if you think all these looks okay I will squash it into "parse async methods".

Looks good. I think you might want to squash only the last two commits together ("bugfix" with the previous one), or just keep them all as they are.

> Decide on stage (e.g. >=3) or popularity, or simply reject all?

>=3 sounds good. Rejecting all would be inconsistent, since it seems we're going to accept the "Async Functions" one. :) It looks fairly popular.

If you're motivated enough to experiment with more riskier proposals, we should probably be able to disable them by default. For instance, by updating the `js2-language-version` variable semantics for the current language versions, and using it consistently. So it would default to ES6, add could additionally be set to different stages of ES7, too.

**Comment by XeCycle** [comment]
Squashed last two.

> updating the js2-language-version variable semantics for the current language versions, and using it consistently. So it would default to ES6, add could additionally be set to different stages of ES7, too.

So we set some version numbers for different stages of ES7?  Pls decide, and I'll make this conditional later.  Playing with old commits are nasty...  they may conflict at any time.  Let's merge first and add that later.

Btw the build failure seems to be failing to install emacs.

**Comment by dgutov** [comment]
> Squashed last two.

Thanks! Merging.

> So we set some version numbers for different stages of ES7? Pls decide, and I'll make this conditional later.

Yes, if you want to work on implementing features.

> Playing with old commits are nasty... they may conflict at any time. Let's merge first and add that later.

Sure. I'm sure we can live with unconditional support for async functions for a while.

> Btw the build failure seems to be failing to install emacs.

Indeed, I had to restart it.

**Comment by dgutov** [comment]
Before I merge, though, please add a NEWS entry (and update the `js2-getter-setter-node` news item).

**Pull request merged**
