### PR TITLE
Classify imported variables

### PR DESCRIPTION
**Pull request by lelit**
This handles most common cases of the `import` statement, see the tests.
I would not be surprised if there is a wider set of syntaxes... if so, please give me samples and I will try to cover them too.

### CODE REVIEW

**Comment by azazel75** [comment]
The complete syntax of the import statement is here http://www.ecma-international.org/ecma-262/6.0/#sec-imports

You may want to signal as error an import like:
```javascript
import {default, foo} from 'module';
```
when the special name `default` is involved in named imports, it should always be aliased, i.e.:
```javascript
import { default as bar,  foo} from `module`;
```

**Comment by azazel75** [comment]
mmm sorry, it doesn't appear to be formally forbidden... maybe a warning will suffice...

**Comment by lelit** [comment]
Thanks for the pointer!
The context of the proposed change is the analysis of the variables usage, the actual parse is done earlier in the process, though. If needed, that warning should be emitted at that time.

**Comment by azazel75** [comment]
oh, maybe I'm completely wrong... it's mentioned on [ExploringJS](http://exploringjs.com/es6/ch_modules.html#sec_importing-exporting-details) but not on the [mozilla reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

**Comment by dgutov** [comment]
Thanks!

> I would not be surprised if there is a wider set of syntaxes... if so, please give me samples and I will try to cover them too.

TBH, I'm not much of an expert on JS syntax these days.

**Comment by lelit** [comment]
Thank you Dmitry!

**Pull request merged**
