### PR TITLE
Makefile: allow overriding $EMACS

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by dgutov** [comment]
Are you sure overriding doesn't work without this change? Because it does here.

**Comment by dunn** [comment]
Something like `EMACS=$(brew --prefix)/bin/emacs make test` wasn't working for me before this change.

**Comment by dgutov** [comment]
The customary usage is `make test EMACS=$(brew --prefix)/bin/emacs`.

**Comment by dunn** [comment]
Oh, right, I was using it as an env var instead of a make variable.

I'll close this, then.  Thanks!

**Pull request closed without merging**
