### PR TITLE
Fix typos in comments and docstrings

### PR DESCRIPTION
**Pull request by lelit**

### CODE REVIEW

**Comment by dgutov** [comment]
Thanks, this looks good. But could you rebase this commit on top of the current `master`?

**Comment by lelit** [comment]
Ouch, sorry, I must have done something weird with git...

**Comment by lelit** [comment]
Ok, I think I got it right now. I actually did a fetch from your repo, but then forgot to merge latest changes into my master...

**Comment by dgutov** [comment]
Thank you.

**Pull request merged**
