### PR TITLE
Adapt async/await to latest master

### PR DESCRIPTION
**Pull request by XeCycle**
async/await support by @mooz has been there for 8 months.  There are some TODO around the lines, which I suppose he intended to improve later, but this has been too long.  Anyway it basically works, let's merge first and resolve problems later (if any).

Btw I guess my changes do not qualify as legally significant.

### CODE REVIEW

**Comment by dgutov** [comment]
Thank you.

> I guess my changes do not qualify as legally significant.

It appears so.

However, I'd really rather have a contributor who would make this feature their responsibility, especially since some details of the syntax could change as it moves through the standardization process. @XeCycle Are you interested in being that person?

Could you answer the comment about `static` + `async` in #185?

**Comment by XeCycle** [comment]
@dgutov I answered that question.

I think I should be able to answer questions on the standard text, or forward the question to tc39 bug tracker.  But currently I am not yet familiar with the parser here in js2-mode, as it is constructed quite different from the grammar specified in the standards.  Did we intend it to be more permissive or for performance?

Well, if you assign this feature to me, expect roughly 1~2 weeks for my answer on questions.

**Comment by dgutov** [comment]
>  But currently I am not yet familiar with the parser here in js2-mode, as it is constructed quite different from the grammar specified in the standards.

I wouldn't say it's too special: it's a recursive-descent parser, adapted from SpiderMonkey.

> Did we intend it to be more permissive or for performance?

Isn't it more or less the same? I'd say we want to only allow valid grammar, as long as it's not too much of a pain to implement, and doesn't slow us down too much.

> if you assign this feature to me, expect roughly 1~2 weeks for my answer on questions

I'd be happy to leave this fix to you, as long as you keep in mind the copyright assignment requirements.

**Comment by XeCycle** [comment]
> I wouldn't say it's too special: it's a recursive-descent parser, adapted from SpiderMonkey.

I have not read ES<=3, no idea if they were different from the beginning or diverged later.  Some grammar productions are given different semantics and/or are defined differently, e.g. the left hand side of an assignment expression is defined by the standard to be a `LeftHandSideExpression` which expands to `NewExpression` or `CallExpression`, but we parse for `ConditionalExpression` and are only checking strict identifier if it is a `js2-name-node`.  This is too permissive.

There are other pieces where our code is permissive to bad code; the above example seems to be avoiding parse the left hand side a second time, so I cannot guess our current policy on standards conformance.

> I'd be happy to leave this fix to you, as long as you keep in mind the copyright assignment requirements.

What about just send me the forms?  I plan to add bind operator sooner or later, so I need it after all.

**Comment by dgutov** [comment]
> I have not read ES<=3, no idea if they were different from the beginning or diverged later.

You could get a better idea by looking at the current SpiderMonkey sources, and comparing `js2-mode` with them. Can't say about this particular problem, but we're lagging behind SM in certain places. Although it could be buggy in this respect as well.

> so I cannot guess our current policy on standards conformance

Use your best judgment, I guess. You can assume that this codebase is not particularly well-maintained.

> What about just send me the forms?

Sure. http://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future

Put in "Emacs" as "the name of the program or package you're contributing to".

**Comment by XeCycle** [comment]
Now working on adding async method support to solve that comment about `static` + `async`.  For the names to be less confusing, I would like to change `js2-getter-setter-node` to `js2-method-node` and have it cover all five types of methods at http://tc39.github.io/ecmascript-asyncawait/#MethodDefinition.  So:

1. how do you like this change?
2. shall that be a separate PR?

btw request form sent, waiting for reply.

**Comment by dgutov** [comment]
> I would like to change js2-getter-setter-node to js2-method-node

Sounds good. Please make it a separate PR, I'll merge it first.

**Comment by XeCycle** [comment]
Taking on async methods, closing this.  Pls wait for another PR :)

**Pull request closed without merging**
